### ISSUE TITLE
awkward require

### ISSUE THREAD

**Issue by stevenvachon** [der-On/es6-promise-series#1]
``` js
require("es6-promise-series")(Promise);
```

is awkward.

I think this would be less restricting and would look like every other package:

``` js
Promise.series = require("es6-promise-series");
//or
var promiseSeries = require("es6-promise-series");
```

**Comment by jedrichards** [comment]
Yep agree. I don't think this lib should have an API based on monkey patching the Promise global. It leads to unpredictable behaviour ... has the global been monkey patched yet, or not? What about in test environments etc.? For my part I think an API like below would be most appropriate,

``` js
import series from 'es6-promise-series'

series([promises])
  .then(...)
```

The `series` function should assume its running in an env with a ES6 `Promise` global present (by all means throw an error if not) ...

At the moment I would be forced to use the library like this,

``` js
const es6PromiseSeries = {}
require('es6-promise-series')(es6PromiseSeries)
es6PromiseSeries.series([promises])
  .then(...)
```

**Comment by der-On** [comment]
Can you make a PR please. I would be happy to have it this way too.

**Comment by jedrichards** [comment]
:+1:
